package com.gr.bk.service.persistence.role;

import com.gr.bk.common.domain.RolePermissionRelDomain;

public interface RolePermissionRelDomainMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_permission_rel
     *
     * @mbggenerated Thu Dec 07 14:29:17 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_permission_rel
     *
     * @mbggenerated Thu Dec 07 14:29:17 CST 2017
     */
    int insert(RolePermissionRelDomain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_permission_rel
     *
     * @mbggenerated Thu Dec 07 14:29:17 CST 2017
     */
    int insertSelective(RolePermissionRelDomain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_permission_rel
     *
     * @mbggenerated Thu Dec 07 14:29:17 CST 2017
     */
    RolePermissionRelDomain selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_permission_rel
     *
     * @mbggenerated Thu Dec 07 14:29:17 CST 2017
     */
    int updateByPrimaryKeySelective(RolePermissionRelDomain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_permission_rel
     *
     * @mbggenerated Thu Dec 07 14:29:17 CST 2017
     */
    int updateByPrimaryKey(RolePermissionRelDomain record);
}