package com.gr.bk.common.domain;

import java.util.Date;

public class PermissionDomain {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.id
     *
     * @mbggenerated Thu Dec 07 14:15:41 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.permission_uuid
     *
     * @mbggenerated Thu Dec 07 14:15:41 CST 2017
     */
    private String permissionUuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.name
     *
     * @mbggenerated Thu Dec 07 14:15:41 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.perms
     *
     * @mbggenerated Thu Dec 07 14:15:41 CST 2017
     */
    private String perms;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.create_user_uuid
     *
     * @mbggenerated Thu Dec 07 14:15:41 CST 2017
     */
    private String createUserUuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.create_time
     *
     * @mbggenerated Thu Dec 07 14:15:41 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.last_update_user_uuid
     *
     * @mbggenerated Thu Dec 07 14:15:41 CST 2017
     */
    private String lastUpdateUserUuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.last_update_time
     *
     * @mbggenerated Thu Dec 07 14:15:41 CST 2017
     */
    private Date lastUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.del_flag
     *
     * @mbggenerated Thu Dec 07 14:15:41 CST 2017
     */
    private Integer delFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission.id
     *
     * @return the value of permission.id
     *
     * @mbggenerated Thu Dec 07 14:15:41 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission.id
     *
     * @param id the value for permission.id
     *
     * @mbggenerated Thu Dec 07 14:15:41 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission.permission_uuid
     *
     * @return the value of permission.permission_uuid
     *
     * @mbggenerated Thu Dec 07 14:15:41 CST 2017
     */
    public String getPermissionUuid() {
        return permissionUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission.permission_uuid
     *
     * @param permissionUuid the value for permission.permission_uuid
     *
     * @mbggenerated Thu Dec 07 14:15:41 CST 2017
     */
    public void setPermissionUuid(String permissionUuid) {
        this.permissionUuid = permissionUuid == null ? null : permissionUuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission.name
     *
     * @return the value of permission.name
     *
     * @mbggenerated Thu Dec 07 14:15:41 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission.name
     *
     * @param name the value for permission.name
     *
     * @mbggenerated Thu Dec 07 14:15:41 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission.perms
     *
     * @return the value of permission.perms
     *
     * @mbggenerated Thu Dec 07 14:15:41 CST 2017
     */
    public String getPerms() {
        return perms;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission.perms
     *
     * @param perms the value for permission.perms
     *
     * @mbggenerated Thu Dec 07 14:15:41 CST 2017
     */
    public void setPerms(String perms) {
        this.perms = perms == null ? null : perms.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission.create_user_uuid
     *
     * @return the value of permission.create_user_uuid
     *
     * @mbggenerated Thu Dec 07 14:15:41 CST 2017
     */
    public String getCreateUserUuid() {
        return createUserUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission.create_user_uuid
     *
     * @param createUserUuid the value for permission.create_user_uuid
     *
     * @mbggenerated Thu Dec 07 14:15:41 CST 2017
     */
    public void setCreateUserUuid(String createUserUuid) {
        this.createUserUuid = createUserUuid == null ? null : createUserUuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission.create_time
     *
     * @return the value of permission.create_time
     *
     * @mbggenerated Thu Dec 07 14:15:41 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission.create_time
     *
     * @param createTime the value for permission.create_time
     *
     * @mbggenerated Thu Dec 07 14:15:41 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission.last_update_user_uuid
     *
     * @return the value of permission.last_update_user_uuid
     *
     * @mbggenerated Thu Dec 07 14:15:41 CST 2017
     */
    public String getLastUpdateUserUuid() {
        return lastUpdateUserUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission.last_update_user_uuid
     *
     * @param lastUpdateUserUuid the value for permission.last_update_user_uuid
     *
     * @mbggenerated Thu Dec 07 14:15:41 CST 2017
     */
    public void setLastUpdateUserUuid(String lastUpdateUserUuid) {
        this.lastUpdateUserUuid = lastUpdateUserUuid == null ? null : lastUpdateUserUuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission.last_update_time
     *
     * @return the value of permission.last_update_time
     *
     * @mbggenerated Thu Dec 07 14:15:41 CST 2017
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission.last_update_time
     *
     * @param lastUpdateTime the value for permission.last_update_time
     *
     * @mbggenerated Thu Dec 07 14:15:41 CST 2017
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission.del_flag
     *
     * @return the value of permission.del_flag
     *
     * @mbggenerated Thu Dec 07 14:15:41 CST 2017
     */
    public Integer getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission.del_flag
     *
     * @param delFlag the value for permission.del_flag
     *
     * @mbggenerated Thu Dec 07 14:15:41 CST 2017
     */
    public void setDelFlag(Integer delFlag) {
        this.delFlag = delFlag;
    }
}