package com.gr.bk.common.domain;

import java.util.Date;

public class RcAreaCode {
	  /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rc_area_code.rc_area_code_id
     *
     * @mbggenerated Wed Nov 22 18:39:11 CST 2017
     */
    private Integer rcAreaCodeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rc_area_code.rc_area_code_uuid
     *
     * @mbggenerated Wed Nov 22 18:39:11 CST 2017
     */
    private String rcAreaCodeUuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rc_area_code.area_code
     *
     * @mbggenerated Wed Nov 22 18:39:11 CST 2017
     */
    private String areaCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rc_area_code.code_name
     *
     * @mbggenerated Wed Nov 22 18:39:11 CST 2017
     */
    private String areaAddr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rc_area_code.remark
     *
     * @mbggenerated Wed Nov 22 18:39:11 CST 2017
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rc_area_code.busi_type
     *
     * @mbggenerated Wed Nov 22 18:39:11 CST 2017
     */
    private String busiType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rc_area_code.create_time
     *
     * @mbggenerated Wed Nov 22 18:39:11 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rc_area_code.update_time
     *
     * @mbggenerated Wed Nov 22 18:39:11 CST 2017
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rc_area_code.del_flag
     *
     * @mbggenerated Wed Nov 22 18:39:11 CST 2017
     */
    private Integer delFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rc_area_code.rc_area_code_id
     *
     * @return the value of rc_area_code.rc_area_code_id
     *
     * @mbggenerated Wed Nov 22 18:39:11 CST 2017
     */
    public Integer getRcAreaCodeId() {
        return rcAreaCodeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rc_area_code.rc_area_code_id
     *
     * @param rcAreaCodeId the value for rc_area_code.rc_area_code_id
     *
     * @mbggenerated Wed Nov 22 18:39:11 CST 2017
     */
    public void setRcAreaCodeId(Integer rcAreaCodeId) {
        this.rcAreaCodeId = rcAreaCodeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rc_area_code.rc_area_code_uuid
     *
     * @return the value of rc_area_code.rc_area_code_uuid
     *
     * @mbggenerated Wed Nov 22 18:39:11 CST 2017
     */
    public String getRcAreaCodeUuid() {
        return rcAreaCodeUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rc_area_code.rc_area_code_uuid
     *
     * @param rcAreaCodeUuid the value for rc_area_code.rc_area_code_uuid
     *
     * @mbggenerated Wed Nov 22 18:39:11 CST 2017
     */
    public void setRcAreaCodeUuid(String rcAreaCodeUuid) {
        this.rcAreaCodeUuid = rcAreaCodeUuid == null ? null : rcAreaCodeUuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rc_area_code.area_code
     *
     * @return the value of rc_area_code.area_code
     *
     * @mbggenerated Wed Nov 22 18:39:11 CST 2017
     */
    public String getAreaCode() {
        return areaCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rc_area_code.area_code
     *
     * @param areaCode the value for rc_area_code.area_code
     *
     * @mbggenerated Wed Nov 22 18:39:11 CST 2017
     */
    public void setAreaCode(String areaCode) {
        this.areaCode = areaCode == null ? null : areaCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rc_area_code.code_name
     *
     * @return the value of rc_area_code.code_name
     *
     * @mbggenerated Wed Nov 22 18:39:11 CST 2017
     */
    public String getAreaAddr() {
        return areaAddr;
    }

    public void setAreaAddr(String areaAddr) {
        this.areaAddr = areaAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rc_area_code.remark
     *
     * @return the value of rc_area_code.remark
     *
     * @mbggenerated Wed Nov 22 18:39:11 CST 2017
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rc_area_code.remark
     *
     * @param remark the value for rc_area_code.remark
     *
     * @mbggenerated Wed Nov 22 18:39:11 CST 2017
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rc_area_code.busi_type
     *
     * @return the value of rc_area_code.busi_type
     *
     * @mbggenerated Wed Nov 22 18:39:11 CST 2017
     */
    public String getBusiType() {
        return busiType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rc_area_code.busi_type
     *
     * @param busiType the value for rc_area_code.busi_type
     *
     * @mbggenerated Wed Nov 22 18:39:11 CST 2017
     */
    public void setBusiType(String busiType) {
        this.busiType = busiType == null ? null : busiType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rc_area_code.create_time
     *
     * @return the value of rc_area_code.create_time
     *
     * @mbggenerated Wed Nov 22 18:39:11 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rc_area_code.create_time
     *
     * @param createTime the value for rc_area_code.create_time
     *
     * @mbggenerated Wed Nov 22 18:39:11 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rc_area_code.update_time
     *
     * @return the value of rc_area_code.update_time
     *
     * @mbggenerated Wed Nov 22 18:39:11 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rc_area_code.update_time
     *
     * @param updateTime the value for rc_area_code.update_time
     *
     * @mbggenerated Wed Nov 22 18:39:11 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rc_area_code.del_flag
     *
     * @return the value of rc_area_code.del_flag
     *
     * @mbggenerated Wed Nov 22 18:39:11 CST 2017
     */
    public Integer getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rc_area_code.del_flag
     *
     * @param delFlag the value for rc_area_code.del_flag
     *
     * @mbggenerated Wed Nov 22 18:39:11 CST 2017
     */
    public void setDelFlag(Integer delFlag) {
        this.delFlag = delFlag;
    }
}