package com.gr.bk.common.domain;

import java.util.Date;

public class RcMetricCodeJudgeDomain {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rc_metric_code_judge.code_judge_id
     *
     * @mbggenerated Wed Nov 29 10:53:03 CST 2017
     */
    private Integer codeJudgeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rc_metric_code_judge.code_judge_uuid
     *
     * @mbggenerated Wed Nov 29 10:53:03 CST 2017
     */
    private String codeJudgeUuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rc_metric_code_judge.rc_metric_code_uuid
     *
     * @mbggenerated Wed Nov 29 10:53:03 CST 2017
     */
    private String rcMetricCodeUuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rc_metric_code_judge.ext_field
     *
     * @mbggenerated Wed Nov 29 10:53:03 CST 2017
     */
    private String extField;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rc_metric_code_judge.j_condition
     *
     * @mbggenerated Wed Nov 29 10:53:03 CST 2017
     */
    private String jCondition;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rc_metric_code_judge.j_value
     *
     * @mbggenerated Wed Nov 29 10:53:03 CST 2017
     */
    private String jValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rc_metric_code_judge.j_result
     *
     * @mbggenerated Wed Nov 29 10:53:03 CST 2017
     */
    private String jResult;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rc_metric_code_judge.remark
     *
     * @mbggenerated Wed Nov 29 10:53:03 CST 2017
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rc_metric_code_judge.create_time
     *
     * @mbggenerated Wed Nov 29 10:53:03 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rc_metric_code_judge.update_time
     *
     * @mbggenerated Wed Nov 29 10:53:03 CST 2017
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rc_metric_code_judge.del_flag
     *
     * @mbggenerated Wed Nov 29 10:53:03 CST 2017
     */
    private Integer delFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rc_metric_code_judge.code_judge_id
     *
     * @return the value of rc_metric_code_judge.code_judge_id
     *
     * @mbggenerated Wed Nov 29 10:53:03 CST 2017
     */
    public Integer getCodeJudgeId() {
        return codeJudgeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rc_metric_code_judge.code_judge_id
     *
     * @param codeJudgeId the value for rc_metric_code_judge.code_judge_id
     *
     * @mbggenerated Wed Nov 29 10:53:03 CST 2017
     */
    public void setCodeJudgeId(Integer codeJudgeId) {
        this.codeJudgeId = codeJudgeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rc_metric_code_judge.code_judge_uuid
     *
     * @return the value of rc_metric_code_judge.code_judge_uuid
     *
     * @mbggenerated Wed Nov 29 10:53:03 CST 2017
     */
    public String getCodeJudgeUuid() {
        return codeJudgeUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rc_metric_code_judge.code_judge_uuid
     *
     * @param codeJudgeUuid the value for rc_metric_code_judge.code_judge_uuid
     *
     * @mbggenerated Wed Nov 29 10:53:03 CST 2017
     */
    public void setCodeJudgeUuid(String codeJudgeUuid) {
        this.codeJudgeUuid = codeJudgeUuid == null ? null : codeJudgeUuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rc_metric_code_judge.rc_metric_code_uuid
     *
     * @return the value of rc_metric_code_judge.rc_metric_code_uuid
     *
     * @mbggenerated Wed Nov 29 10:53:03 CST 2017
     */
    public String getRcMetricCodeUuid() {
        return rcMetricCodeUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rc_metric_code_judge.rc_metric_code_uuid
     *
     * @param rcMetricCodeUuid the value for rc_metric_code_judge.rc_metric_code_uuid
     *
     * @mbggenerated Wed Nov 29 10:53:03 CST 2017
     */
    public void setRcMetricCodeUuid(String rcMetricCodeUuid) {
        this.rcMetricCodeUuid = rcMetricCodeUuid == null ? null : rcMetricCodeUuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rc_metric_code_judge.ext_field
     *
     * @return the value of rc_metric_code_judge.ext_field
     *
     * @mbggenerated Wed Nov 29 10:53:03 CST 2017
     */
    public String getExtField() {
        return extField;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rc_metric_code_judge.ext_field
     *
     * @param extField the value for rc_metric_code_judge.ext_field
     *
     * @mbggenerated Wed Nov 29 10:53:03 CST 2017
     */
    public void setExtField(String extField) {
        this.extField = extField == null ? null : extField.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rc_metric_code_judge.j_condition
     *
     * @return the value of rc_metric_code_judge.j_condition
     *
     * @mbggenerated Wed Nov 29 10:53:03 CST 2017
     */
    public String getjCondition() {
        return jCondition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rc_metric_code_judge.j_condition
     *
     * @param jCondition the value for rc_metric_code_judge.j_condition
     *
     * @mbggenerated Wed Nov 29 10:53:03 CST 2017
     */
    public void setjCondition(String jCondition) {
        this.jCondition = jCondition == null ? null : jCondition.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rc_metric_code_judge.j_value
     *
     * @return the value of rc_metric_code_judge.j_value
     *
     * @mbggenerated Wed Nov 29 10:53:03 CST 2017
     */
    public String getjValue() {
        return jValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rc_metric_code_judge.j_value
     *
     * @param jValue the value for rc_metric_code_judge.j_value
     *
     * @mbggenerated Wed Nov 29 10:53:03 CST 2017
     */
    public void setjValue(String jValue) {
        this.jValue = jValue == null ? null : jValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rc_metric_code_judge.j_result
     *
     * @return the value of rc_metric_code_judge.j_result
     *
     * @mbggenerated Wed Nov 29 10:53:03 CST 2017
     */
    public String getjResult() {
        return jResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rc_metric_code_judge.j_result
     *
     * @param jResult the value for rc_metric_code_judge.j_result
     *
     * @mbggenerated Wed Nov 29 10:53:03 CST 2017
     */
    public void setjResult(String jResult) {
        this.jResult = jResult == null ? null : jResult.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rc_metric_code_judge.remark
     *
     * @return the value of rc_metric_code_judge.remark
     *
     * @mbggenerated Wed Nov 29 10:53:03 CST 2017
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rc_metric_code_judge.remark
     *
     * @param remark the value for rc_metric_code_judge.remark
     *
     * @mbggenerated Wed Nov 29 10:53:03 CST 2017
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rc_metric_code_judge.create_time
     *
     * @return the value of rc_metric_code_judge.create_time
     *
     * @mbggenerated Wed Nov 29 10:53:03 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rc_metric_code_judge.create_time
     *
     * @param createTime the value for rc_metric_code_judge.create_time
     *
     * @mbggenerated Wed Nov 29 10:53:03 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rc_metric_code_judge.update_time
     *
     * @return the value of rc_metric_code_judge.update_time
     *
     * @mbggenerated Wed Nov 29 10:53:03 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rc_metric_code_judge.update_time
     *
     * @param updateTime the value for rc_metric_code_judge.update_time
     *
     * @mbggenerated Wed Nov 29 10:53:03 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rc_metric_code_judge.del_flag
     *
     * @return the value of rc_metric_code_judge.del_flag
     *
     * @mbggenerated Wed Nov 29 10:53:03 CST 2017
     */
    public Integer getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rc_metric_code_judge.del_flag
     *
     * @param delFlag the value for rc_metric_code_judge.del_flag
     *
     * @mbggenerated Wed Nov 29 10:53:03 CST 2017
     */
    public void setDelFlag(Integer delFlag) {
        this.delFlag = delFlag;
    }
}