package com.gr.bk.common.domain;

import java.util.Date;

public class RcMetricCodeDomain {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rc_metric_code.rc_metric_code_id
     *
     * @mbggenerated Wed Nov 29 14:34:15 CST 2017
     */
    private Integer rcMetricCodeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rc_metric_code.rc_metric_code_uuid
     *
     * @mbggenerated Wed Nov 29 14:34:15 CST 2017
     */
    private String rcMetricCodeUuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rc_metric_code.rc_metric_uuid
     *
     * @mbggenerated Wed Nov 29 14:34:15 CST 2017
     */
    private String rcMetricUuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rc_metric_code.code
     *
     * @mbggenerated Wed Nov 29 14:34:15 CST 2017
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rc_metric_code.code_name
     *
     * @mbggenerated Wed Nov 29 14:34:15 CST 2017
     */
    private String codeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rc_metric_code.code_desc
     *
     * @mbggenerated Wed Nov 29 14:34:15 CST 2017
     */
    private String codeDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rc_metric_code.ref_code
     *
     * @mbggenerated Wed Nov 29 14:34:15 CST 2017
     */
    private String refCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rc_metric_code.ref_table
     *
     * @mbggenerated Wed Nov 29 14:34:15 CST 2017
     */
    private String refTable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rc_metric_code.sort_num
     *
     * @mbggenerated Wed Nov 29 14:34:15 CST 2017
     */
    private Integer sortNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rc_metric_code.j_condition
     *
     * @mbggenerated Wed Nov 29 14:34:15 CST 2017
     */
    private String jCondition;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rc_metric_code.j_value
     *
     * @mbggenerated Wed Nov 29 14:34:15 CST 2017
     */
    private String jValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rc_metric_code.j_result
     *
     * @mbggenerated Wed Nov 29 14:34:15 CST 2017
     */
    private String jResult;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rc_metric_code.remark
     *
     * @mbggenerated Wed Nov 29 14:34:15 CST 2017
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rc_metric_code.is_ref
     *
     * @mbggenerated Wed Nov 29 14:34:15 CST 2017
     */
    private Integer isRef;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rc_metric_code.code_level
     *
     * @mbggenerated Wed Nov 29 14:34:15 CST 2017
     */
    private Integer codeLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rc_metric_code.create_time
     *
     * @mbggenerated Wed Nov 29 14:34:15 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rc_metric_code.update_time
     *
     * @mbggenerated Wed Nov 29 14:34:15 CST 2017
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rc_metric_code.del_flag
     *
     * @mbggenerated Wed Nov 29 14:34:15 CST 2017
     */
    private Integer delFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rc_metric_code.rc_metric_code_id
     *
     * @return the value of rc_metric_code.rc_metric_code_id
     *
     * @mbggenerated Wed Nov 29 14:34:15 CST 2017
     */
    public Integer getRcMetricCodeId() {
        return rcMetricCodeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rc_metric_code.rc_metric_code_id
     *
     * @param rcMetricCodeId the value for rc_metric_code.rc_metric_code_id
     *
     * @mbggenerated Wed Nov 29 14:34:15 CST 2017
     */
    public void setRcMetricCodeId(Integer rcMetricCodeId) {
        this.rcMetricCodeId = rcMetricCodeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rc_metric_code.rc_metric_code_uuid
     *
     * @return the value of rc_metric_code.rc_metric_code_uuid
     *
     * @mbggenerated Wed Nov 29 14:34:15 CST 2017
     */
    public String getRcMetricCodeUuid() {
        return rcMetricCodeUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rc_metric_code.rc_metric_code_uuid
     *
     * @param rcMetricCodeUuid the value for rc_metric_code.rc_metric_code_uuid
     *
     * @mbggenerated Wed Nov 29 14:34:15 CST 2017
     */
    public void setRcMetricCodeUuid(String rcMetricCodeUuid) {
        this.rcMetricCodeUuid = rcMetricCodeUuid == null ? null : rcMetricCodeUuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rc_metric_code.rc_metric_uuid
     *
     * @return the value of rc_metric_code.rc_metric_uuid
     *
     * @mbggenerated Wed Nov 29 14:34:15 CST 2017
     */
    public String getRcMetricUuid() {
        return rcMetricUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rc_metric_code.rc_metric_uuid
     *
     * @param rcMetricUuid the value for rc_metric_code.rc_metric_uuid
     *
     * @mbggenerated Wed Nov 29 14:34:15 CST 2017
     */
    public void setRcMetricUuid(String rcMetricUuid) {
        this.rcMetricUuid = rcMetricUuid == null ? null : rcMetricUuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rc_metric_code.code
     *
     * @return the value of rc_metric_code.code
     *
     * @mbggenerated Wed Nov 29 14:34:15 CST 2017
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rc_metric_code.code
     *
     * @param code the value for rc_metric_code.code
     *
     * @mbggenerated Wed Nov 29 14:34:15 CST 2017
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rc_metric_code.code_name
     *
     * @return the value of rc_metric_code.code_name
     *
     * @mbggenerated Wed Nov 29 14:34:15 CST 2017
     */
    public String getCodeName() {
        return codeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rc_metric_code.code_name
     *
     * @param codeName the value for rc_metric_code.code_name
     *
     * @mbggenerated Wed Nov 29 14:34:15 CST 2017
     */
    public void setCodeName(String codeName) {
        this.codeName = codeName == null ? null : codeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rc_metric_code.code_desc
     *
     * @return the value of rc_metric_code.code_desc
     *
     * @mbggenerated Wed Nov 29 14:34:15 CST 2017
     */
    public String getCodeDesc() {
        return codeDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rc_metric_code.code_desc
     *
     * @param codeDesc the value for rc_metric_code.code_desc
     *
     * @mbggenerated Wed Nov 29 14:34:15 CST 2017
     */
    public void setCodeDesc(String codeDesc) {
        this.codeDesc = codeDesc == null ? null : codeDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rc_metric_code.ref_code
     *
     * @return the value of rc_metric_code.ref_code
     *
     * @mbggenerated Wed Nov 29 14:34:15 CST 2017
     */
    public String getRefCode() {
        return refCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rc_metric_code.ref_code
     *
     * @param refCode the value for rc_metric_code.ref_code
     *
     * @mbggenerated Wed Nov 29 14:34:15 CST 2017
     */
    public void setRefCode(String refCode) {
        this.refCode = refCode == null ? null : refCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rc_metric_code.ref_table
     *
     * @return the value of rc_metric_code.ref_table
     *
     * @mbggenerated Wed Nov 29 14:34:15 CST 2017
     */
    public String getRefTable() {
        return refTable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rc_metric_code.ref_table
     *
     * @param refTable the value for rc_metric_code.ref_table
     *
     * @mbggenerated Wed Nov 29 14:34:15 CST 2017
     */
    public void setRefTable(String refTable) {
        this.refTable = refTable == null ? null : refTable.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rc_metric_code.sort_num
     *
     * @return the value of rc_metric_code.sort_num
     *
     * @mbggenerated Wed Nov 29 14:34:15 CST 2017
     */
    public Integer getSortNum() {
        return sortNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rc_metric_code.sort_num
     *
     * @param sortNum the value for rc_metric_code.sort_num
     *
     * @mbggenerated Wed Nov 29 14:34:15 CST 2017
     */
    public void setSortNum(Integer sortNum) {
        this.sortNum = sortNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rc_metric_code.j_condition
     *
     * @return the value of rc_metric_code.j_condition
     *
     * @mbggenerated Wed Nov 29 14:34:15 CST 2017
     */
    public String getjCondition() {
        return jCondition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rc_metric_code.j_condition
     *
     * @param jCondition the value for rc_metric_code.j_condition
     *
     * @mbggenerated Wed Nov 29 14:34:15 CST 2017
     */
    public void setjCondition(String jCondition) {
        this.jCondition = jCondition == null ? null : jCondition.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rc_metric_code.j_value
     *
     * @return the value of rc_metric_code.j_value
     *
     * @mbggenerated Wed Nov 29 14:34:15 CST 2017
     */
    public String getjValue() {
        return jValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rc_metric_code.j_value
     *
     * @param jValue the value for rc_metric_code.j_value
     *
     * @mbggenerated Wed Nov 29 14:34:15 CST 2017
     */
    public void setjValue(String jValue) {
        this.jValue = jValue == null ? null : jValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rc_metric_code.j_result
     *
     * @return the value of rc_metric_code.j_result
     *
     * @mbggenerated Wed Nov 29 14:34:15 CST 2017
     */
    public String getjResult() {
        return jResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rc_metric_code.j_result
     *
     * @param jResult the value for rc_metric_code.j_result
     *
     * @mbggenerated Wed Nov 29 14:34:15 CST 2017
     */
    public void setjResult(String jResult) {
        this.jResult = jResult == null ? null : jResult.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rc_metric_code.remark
     *
     * @return the value of rc_metric_code.remark
     *
     * @mbggenerated Wed Nov 29 14:34:15 CST 2017
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rc_metric_code.remark
     *
     * @param remark the value for rc_metric_code.remark
     *
     * @mbggenerated Wed Nov 29 14:34:15 CST 2017
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rc_metric_code.is_ref
     *
     * @return the value of rc_metric_code.is_ref
     *
     * @mbggenerated Wed Nov 29 14:34:15 CST 2017
     */
    public Integer getIsRef() {
        return isRef;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rc_metric_code.is_ref
     *
     * @param isRef the value for rc_metric_code.is_ref
     *
     * @mbggenerated Wed Nov 29 14:34:15 CST 2017
     */
    public void setIsRef(Integer isRef) {
        this.isRef = isRef;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rc_metric_code.code_level
     *
     * @return the value of rc_metric_code.code_level
     *
     * @mbggenerated Wed Nov 29 14:34:15 CST 2017
     */
    public Integer getCodeLevel() {
        return codeLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rc_metric_code.code_level
     *
     * @param codeLevel the value for rc_metric_code.code_level
     *
     * @mbggenerated Wed Nov 29 14:34:15 CST 2017
     */
    public void setCodeLevel(Integer codeLevel) {
        this.codeLevel = codeLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rc_metric_code.create_time
     *
     * @return the value of rc_metric_code.create_time
     *
     * @mbggenerated Wed Nov 29 14:34:15 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rc_metric_code.create_time
     *
     * @param createTime the value for rc_metric_code.create_time
     *
     * @mbggenerated Wed Nov 29 14:34:15 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rc_metric_code.update_time
     *
     * @return the value of rc_metric_code.update_time
     *
     * @mbggenerated Wed Nov 29 14:34:15 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rc_metric_code.update_time
     *
     * @param updateTime the value for rc_metric_code.update_time
     *
     * @mbggenerated Wed Nov 29 14:34:15 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rc_metric_code.del_flag
     *
     * @return the value of rc_metric_code.del_flag
     *
     * @mbggenerated Wed Nov 29 14:34:15 CST 2017
     */
    public Integer getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rc_metric_code.del_flag
     *
     * @param delFlag the value for rc_metric_code.del_flag
     *
     * @mbggenerated Wed Nov 29 14:34:15 CST 2017
     */
    public void setDelFlag(Integer delFlag) {
        this.delFlag = delFlag;
    }
}