package com.gr.bk.common.domain;

import java.util.Date;

public class RolePermissionRelDomain {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_permission_rel.id
     *
     * @mbggenerated Thu Dec 07 14:29:17 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_permission_rel.role_permission_rel_uuid
     *
     * @mbggenerated Thu Dec 07 14:29:17 CST 2017
     */
    private String rolePermissionRelUuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_permission_rel.role_uuid
     *
     * @mbggenerated Thu Dec 07 14:29:17 CST 2017
     */
    private String roleUuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_permission_rel.permission_uuid
     *
     * @mbggenerated Thu Dec 07 14:29:17 CST 2017
     */
    private String permissionUuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_permission_rel.create_user_uuid
     *
     * @mbggenerated Thu Dec 07 14:29:17 CST 2017
     */
    private String createUserUuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_permission_rel.create_time
     *
     * @mbggenerated Thu Dec 07 14:29:17 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_permission_rel.last_update_user_uuid
     *
     * @mbggenerated Thu Dec 07 14:29:17 CST 2017
     */
    private String lastUpdateUserUuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_permission_rel.last_update_time
     *
     * @mbggenerated Thu Dec 07 14:29:17 CST 2017
     */
    private Date lastUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_permission_rel.del_flag
     *
     * @mbggenerated Thu Dec 07 14:29:17 CST 2017
     */
    private Integer delFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_permission_rel.id
     *
     * @return the value of role_permission_rel.id
     *
     * @mbggenerated Thu Dec 07 14:29:17 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_permission_rel.id
     *
     * @param id the value for role_permission_rel.id
     *
     * @mbggenerated Thu Dec 07 14:29:17 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_permission_rel.role_permission_rel_uuid
     *
     * @return the value of role_permission_rel.role_permission_rel_uuid
     *
     * @mbggenerated Thu Dec 07 14:29:17 CST 2017
     */
    public String getRolePermissionRelUuid() {
        return rolePermissionRelUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_permission_rel.role_permission_rel_uuid
     *
     * @param rolePermissionRelUuid the value for role_permission_rel.role_permission_rel_uuid
     *
     * @mbggenerated Thu Dec 07 14:29:17 CST 2017
     */
    public void setRolePermissionRelUuid(String rolePermissionRelUuid) {
        this.rolePermissionRelUuid = rolePermissionRelUuid == null ? null : rolePermissionRelUuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_permission_rel.role_uuid
     *
     * @return the value of role_permission_rel.role_uuid
     *
     * @mbggenerated Thu Dec 07 14:29:17 CST 2017
     */
    public String getRoleUuid() {
        return roleUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_permission_rel.role_uuid
     *
     * @param roleUuid the value for role_permission_rel.role_uuid
     *
     * @mbggenerated Thu Dec 07 14:29:17 CST 2017
     */
    public void setRoleUuid(String roleUuid) {
        this.roleUuid = roleUuid == null ? null : roleUuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_permission_rel.permission_uuid
     *
     * @return the value of role_permission_rel.permission_uuid
     *
     * @mbggenerated Thu Dec 07 14:29:17 CST 2017
     */
    public String getPermissionUuid() {
        return permissionUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_permission_rel.permission_uuid
     *
     * @param permissionUuid the value for role_permission_rel.permission_uuid
     *
     * @mbggenerated Thu Dec 07 14:29:17 CST 2017
     */
    public void setPermissionUuid(String permissionUuid) {
        this.permissionUuid = permissionUuid == null ? null : permissionUuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_permission_rel.create_user_uuid
     *
     * @return the value of role_permission_rel.create_user_uuid
     *
     * @mbggenerated Thu Dec 07 14:29:17 CST 2017
     */
    public String getCreateUserUuid() {
        return createUserUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_permission_rel.create_user_uuid
     *
     * @param createUserUuid the value for role_permission_rel.create_user_uuid
     *
     * @mbggenerated Thu Dec 07 14:29:17 CST 2017
     */
    public void setCreateUserUuid(String createUserUuid) {
        this.createUserUuid = createUserUuid == null ? null : createUserUuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_permission_rel.create_time
     *
     * @return the value of role_permission_rel.create_time
     *
     * @mbggenerated Thu Dec 07 14:29:17 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_permission_rel.create_time
     *
     * @param createTime the value for role_permission_rel.create_time
     *
     * @mbggenerated Thu Dec 07 14:29:17 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_permission_rel.last_update_user_uuid
     *
     * @return the value of role_permission_rel.last_update_user_uuid
     *
     * @mbggenerated Thu Dec 07 14:29:17 CST 2017
     */
    public String getLastUpdateUserUuid() {
        return lastUpdateUserUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_permission_rel.last_update_user_uuid
     *
     * @param lastUpdateUserUuid the value for role_permission_rel.last_update_user_uuid
     *
     * @mbggenerated Thu Dec 07 14:29:17 CST 2017
     */
    public void setLastUpdateUserUuid(String lastUpdateUserUuid) {
        this.lastUpdateUserUuid = lastUpdateUserUuid == null ? null : lastUpdateUserUuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_permission_rel.last_update_time
     *
     * @return the value of role_permission_rel.last_update_time
     *
     * @mbggenerated Thu Dec 07 14:29:17 CST 2017
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_permission_rel.last_update_time
     *
     * @param lastUpdateTime the value for role_permission_rel.last_update_time
     *
     * @mbggenerated Thu Dec 07 14:29:17 CST 2017
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_permission_rel.del_flag
     *
     * @return the value of role_permission_rel.del_flag
     *
     * @mbggenerated Thu Dec 07 14:29:17 CST 2017
     */
    public Integer getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_permission_rel.del_flag
     *
     * @param delFlag the value for role_permission_rel.del_flag
     *
     * @mbggenerated Thu Dec 07 14:29:17 CST 2017
     */
    public void setDelFlag(Integer delFlag) {
        this.delFlag = delFlag;
    }
}