package com.gr.bk.common.domain;

import java.util.Date;

public class RoleDomain {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.id
     *
     * @mbggenerated Thu Dec 07 14:11:58 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.role_uuid
     *
     * @mbggenerated Thu Dec 07 14:11:58 CST 2017
     */
    private String roleUuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.role_name
     *
     * @mbggenerated Thu Dec 07 14:11:58 CST 2017
     */
    private String roleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.role_code
     *
     * @mbggenerated Thu Dec 07 14:11:58 CST 2017
     */
    private String roleCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.create_user_uuid
     *
     * @mbggenerated Thu Dec 07 14:11:58 CST 2017
     */
    private String createUserUuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.create_time
     *
     * @mbggenerated Thu Dec 07 14:11:58 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.last_update_user_uuid
     *
     * @mbggenerated Thu Dec 07 14:11:58 CST 2017
     */
    private String lastUpdateUserUuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.last_update_time
     *
     * @mbggenerated Thu Dec 07 14:11:58 CST 2017
     */
    private Date lastUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.del_flag
     *
     * @mbggenerated Thu Dec 07 14:11:58 CST 2017
     */
    private String delFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.id
     *
     * @return the value of role.id
     *
     * @mbggenerated Thu Dec 07 14:11:58 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.id
     *
     * @param id the value for role.id
     *
     * @mbggenerated Thu Dec 07 14:11:58 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.role_uuid
     *
     * @return the value of role.role_uuid
     *
     * @mbggenerated Thu Dec 07 14:11:58 CST 2017
     */
    public String getRoleUuid() {
        return roleUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.role_uuid
     *
     * @param roleUuid the value for role.role_uuid
     *
     * @mbggenerated Thu Dec 07 14:11:58 CST 2017
     */
    public void setRoleUuid(String roleUuid) {
        this.roleUuid = roleUuid == null ? null : roleUuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.role_name
     *
     * @return the value of role.role_name
     *
     * @mbggenerated Thu Dec 07 14:11:58 CST 2017
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.role_name
     *
     * @param roleName the value for role.role_name
     *
     * @mbggenerated Thu Dec 07 14:11:58 CST 2017
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.role_code
     *
     * @return the value of role.role_code
     *
     * @mbggenerated Thu Dec 07 14:11:58 CST 2017
     */
    public String getRoleCode() {
        return roleCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.role_code
     *
     * @param roleCode the value for role.role_code
     *
     * @mbggenerated Thu Dec 07 14:11:58 CST 2017
     */
    public void setRoleCode(String roleCode) {
        this.roleCode = roleCode == null ? null : roleCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.create_user_uuid
     *
     * @return the value of role.create_user_uuid
     *
     * @mbggenerated Thu Dec 07 14:11:58 CST 2017
     */
    public String getCreateUserUuid() {
        return createUserUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.create_user_uuid
     *
     * @param createUserUuid the value for role.create_user_uuid
     *
     * @mbggenerated Thu Dec 07 14:11:58 CST 2017
     */
    public void setCreateUserUuid(String createUserUuid) {
        this.createUserUuid = createUserUuid == null ? null : createUserUuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.create_time
     *
     * @return the value of role.create_time
     *
     * @mbggenerated Thu Dec 07 14:11:58 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.create_time
     *
     * @param createTime the value for role.create_time
     *
     * @mbggenerated Thu Dec 07 14:11:58 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.last_update_user_uuid
     *
     * @return the value of role.last_update_user_uuid
     *
     * @mbggenerated Thu Dec 07 14:11:58 CST 2017
     */
    public String getLastUpdateUserUuid() {
        return lastUpdateUserUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.last_update_user_uuid
     *
     * @param lastUpdateUserUuid the value for role.last_update_user_uuid
     *
     * @mbggenerated Thu Dec 07 14:11:58 CST 2017
     */
    public void setLastUpdateUserUuid(String lastUpdateUserUuid) {
        this.lastUpdateUserUuid = lastUpdateUserUuid == null ? null : lastUpdateUserUuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.last_update_time
     *
     * @return the value of role.last_update_time
     *
     * @mbggenerated Thu Dec 07 14:11:58 CST 2017
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.last_update_time
     *
     * @param lastUpdateTime the value for role.last_update_time
     *
     * @mbggenerated Thu Dec 07 14:11:58 CST 2017
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.del_flag
     *
     * @return the value of role.del_flag
     *
     * @mbggenerated Thu Dec 07 14:11:58 CST 2017
     */
    public String getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.del_flag
     *
     * @param delFlag the value for role.del_flag
     *
     * @mbggenerated Thu Dec 07 14:11:58 CST 2017
     */
    public void setDelFlag(String delFlag) {
        this.delFlag = delFlag == null ? null : delFlag.trim();
    }

    @Override
    public String toString() {
        return "RoleDomain{" +
                "id=" + id +
                ", roleUuid='" + roleUuid + '\'' +
                ", roleName='" + roleName + '\'' +
                ", roleCode='" + roleCode + '\'' +
                ", createUserUuid='" + createUserUuid + '\'' +
                ", createTime=" + createTime +
                ", lastUpdateUserUuid='" + lastUpdateUserUuid + '\'' +
                ", lastUpdateTime=" + lastUpdateTime +
                ", delFlag='" + delFlag + '\'' +
                '}';
    }
}