package com.gr.bk.common.domain;

import java.util.Date;

public class UserRoleRelDomain {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_role_rel.id
     *
     * @mbggenerated Thu Dec 07 14:32:02 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_role_rel.user_role_rel_uuid
     *
     * @mbggenerated Thu Dec 07 14:32:02 CST 2017
     */
    private String userRoleRelUuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_role_rel.user_uuid
     *
     * @mbggenerated Thu Dec 07 14:32:02 CST 2017
     */
    private String userUuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_role_rel.role_uuid
     *
     * @mbggenerated Thu Dec 07 14:32:02 CST 2017
     */
    private String roleUuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_role_rel.create_user_uuid
     *
     * @mbggenerated Thu Dec 07 14:32:02 CST 2017
     */
    private String createUserUuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_role_rel.create_time
     *
     * @mbggenerated Thu Dec 07 14:32:02 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_role_rel.last_update_user_uuid
     *
     * @mbggenerated Thu Dec 07 14:32:02 CST 2017
     */
    private String lastUpdateUserUuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_role_rel.last_update_time
     *
     * @mbggenerated Thu Dec 07 14:32:02 CST 2017
     */
    private Date lastUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_role_rel.del_flag
     *
     * @mbggenerated Thu Dec 07 14:32:02 CST 2017
     */
    private Integer delFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_role_rel.id
     *
     * @return the value of user_role_rel.id
     *
     * @mbggenerated Thu Dec 07 14:32:02 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_role_rel.id
     *
     * @param id the value for user_role_rel.id
     *
     * @mbggenerated Thu Dec 07 14:32:02 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_role_rel.user_role_rel_uuid
     *
     * @return the value of user_role_rel.user_role_rel_uuid
     *
     * @mbggenerated Thu Dec 07 14:32:02 CST 2017
     */
    public String getUserRoleRelUuid() {
        return userRoleRelUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_role_rel.user_role_rel_uuid
     *
     * @param userRoleRelUuid the value for user_role_rel.user_role_rel_uuid
     *
     * @mbggenerated Thu Dec 07 14:32:02 CST 2017
     */
    public void setUserRoleRelUuid(String userRoleRelUuid) {
        this.userRoleRelUuid = userRoleRelUuid == null ? null : userRoleRelUuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_role_rel.user_uuid
     *
     * @return the value of user_role_rel.user_uuid
     *
     * @mbggenerated Thu Dec 07 14:32:02 CST 2017
     */
    public String getUserUuid() {
        return userUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_role_rel.user_uuid
     *
     * @param userUuid the value for user_role_rel.user_uuid
     *
     * @mbggenerated Thu Dec 07 14:32:02 CST 2017
     */
    public void setUserUuid(String userUuid) {
        this.userUuid = userUuid == null ? null : userUuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_role_rel.role_uuid
     *
     * @return the value of user_role_rel.role_uuid
     *
     * @mbggenerated Thu Dec 07 14:32:02 CST 2017
     */
    public String getRoleUuid() {
        return roleUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_role_rel.role_uuid
     *
     * @param roleUuid the value for user_role_rel.role_uuid
     *
     * @mbggenerated Thu Dec 07 14:32:02 CST 2017
     */
    public void setRoleUuid(String roleUuid) {
        this.roleUuid = roleUuid == null ? null : roleUuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_role_rel.create_user_uuid
     *
     * @return the value of user_role_rel.create_user_uuid
     *
     * @mbggenerated Thu Dec 07 14:32:02 CST 2017
     */
    public String getCreateUserUuid() {
        return createUserUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_role_rel.create_user_uuid
     *
     * @param createUserUuid the value for user_role_rel.create_user_uuid
     *
     * @mbggenerated Thu Dec 07 14:32:02 CST 2017
     */
    public void setCreateUserUuid(String createUserUuid) {
        this.createUserUuid = createUserUuid == null ? null : createUserUuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_role_rel.create_time
     *
     * @return the value of user_role_rel.create_time
     *
     * @mbggenerated Thu Dec 07 14:32:02 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_role_rel.create_time
     *
     * @param createTime the value for user_role_rel.create_time
     *
     * @mbggenerated Thu Dec 07 14:32:02 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_role_rel.last_update_user_uuid
     *
     * @return the value of user_role_rel.last_update_user_uuid
     *
     * @mbggenerated Thu Dec 07 14:32:02 CST 2017
     */
    public String getLastUpdateUserUuid() {
        return lastUpdateUserUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_role_rel.last_update_user_uuid
     *
     * @param lastUpdateUserUuid the value for user_role_rel.last_update_user_uuid
     *
     * @mbggenerated Thu Dec 07 14:32:02 CST 2017
     */
    public void setLastUpdateUserUuid(String lastUpdateUserUuid) {
        this.lastUpdateUserUuid = lastUpdateUserUuid == null ? null : lastUpdateUserUuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_role_rel.last_update_time
     *
     * @return the value of user_role_rel.last_update_time
     *
     * @mbggenerated Thu Dec 07 14:32:02 CST 2017
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_role_rel.last_update_time
     *
     * @param lastUpdateTime the value for user_role_rel.last_update_time
     *
     * @mbggenerated Thu Dec 07 14:32:02 CST 2017
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_role_rel.del_flag
     *
     * @return the value of user_role_rel.del_flag
     *
     * @mbggenerated Thu Dec 07 14:32:02 CST 2017
     */
    public Integer getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_role_rel.del_flag
     *
     * @param delFlag the value for user_role_rel.del_flag
     *
     * @mbggenerated Thu Dec 07 14:32:02 CST 2017
     */
    public void setDelFlag(Integer delFlag) {
        this.delFlag = delFlag;
    }
}