package com.gr.bk.service.persistence.permission;

import com.gr.bk.common.domain.PermissionDomain;

import java.util.Set;

public interface PermissionDomainMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission
     *
     * @mbggenerated Thu Dec 07 14:15:41 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission
     *
     * @mbggenerated Thu Dec 07 14:15:41 CST 2017
     */
    int insert(PermissionDomain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission
     *
     * @mbggenerated Thu Dec 07 14:15:41 CST 2017
     */
    int insertSelective(PermissionDomain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission
     *
     * @mbggenerated Thu Dec 07 14:15:41 CST 2017
     */
    PermissionDomain selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission
     *
     * @mbggenerated Thu Dec 07 14:15:41 CST 2017
     */
    int updateByPrimaryKeySelective(PermissionDomain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission
     *
     * @mbggenerated Thu Dec 07 14:15:41 CST 2017
     */
    int updateByPrimaryKey(PermissionDomain record);

    Set<String> queryPermission(String userUuid);
}