package com.gr.bk.service.persistence.user;

import com.gr.bk.common.domain.UserRoleRelDomain;

public interface UserRoleRelDomainMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role_rel
     *
     * @mbggenerated Thu Dec 07 14:32:02 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role_rel
     *
     * @mbggenerated Thu Dec 07 14:32:02 CST 2017
     */
    int insert(UserRoleRelDomain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role_rel
     *
     * @mbggenerated Thu Dec 07 14:32:02 CST 2017
     */
    int insertSelective(UserRoleRelDomain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role_rel
     *
     * @mbggenerated Thu Dec 07 14:32:02 CST 2017
     */
    UserRoleRelDomain selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role_rel
     *
     * @mbggenerated Thu Dec 07 14:32:02 CST 2017
     */
    int updateByPrimaryKeySelective(UserRoleRelDomain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role_rel
     *
     * @mbggenerated Thu Dec 07 14:32:02 CST 2017
     */
    int updateByPrimaryKey(UserRoleRelDomain record);
}