package com.rctest;

import java.util.Date;

public class RcModelArea {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rc_model_area.rc_model_area_id
     *
     * @mbggenerated Mon Oct 30 09:40:36 CST 2017
     */
    private Integer rcModelAreaId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rc_model_area.rc_model_area_uuid
     *
     * @mbggenerated Mon Oct 30 09:40:36 CST 2017
     */
    private String rcModelAreaUuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rc_model_area.rc_model_uuid
     *
     * @mbggenerated Mon Oct 30 09:40:36 CST 2017
     */
    private String rcModelUuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rc_model_area.busi_type
     *
     * @mbggenerated Mon Oct 30 09:40:36 CST 2017
     */
    private String busiType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rc_model_area.area_code
     *
     * @mbggenerated Mon Oct 30 09:40:36 CST 2017
     */
    private String areaCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rc_model_area.area_name
     *
     * @mbggenerated Mon Oct 30 09:40:36 CST 2017
     */
    private String areaName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rc_model_area.remark
     *
     * @mbggenerated Mon Oct 30 09:40:36 CST 2017
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rc_model_area.create_time
     *
     * @mbggenerated Mon Oct 30 09:40:36 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rc_model_area.update_time
     *
     * @mbggenerated Mon Oct 30 09:40:36 CST 2017
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rc_model_area.del_flag
     *
     * @mbggenerated Mon Oct 30 09:40:36 CST 2017
     */
    private Integer delFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rc_model_area.rc_model_area_id
     *
     * @return the value of rc_model_area.rc_model_area_id
     *
     * @mbggenerated Mon Oct 30 09:40:36 CST 2017
     */
    public Integer getRcModelAreaId() {
        return rcModelAreaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rc_model_area.rc_model_area_id
     *
     * @param rcModelAreaId the value for rc_model_area.rc_model_area_id
     *
     * @mbggenerated Mon Oct 30 09:40:36 CST 2017
     */
    public void setRcModelAreaId(Integer rcModelAreaId) {
        this.rcModelAreaId = rcModelAreaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rc_model_area.rc_model_area_uuid
     *
     * @return the value of rc_model_area.rc_model_area_uuid
     *
     * @mbggenerated Mon Oct 30 09:40:36 CST 2017
     */
    public String getRcModelAreaUuid() {
        return rcModelAreaUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rc_model_area.rc_model_area_uuid
     *
     * @param rcModelAreaUuid the value for rc_model_area.rc_model_area_uuid
     *
     * @mbggenerated Mon Oct 30 09:40:36 CST 2017
     */
    public void setRcModelAreaUuid(String rcModelAreaUuid) {
        this.rcModelAreaUuid = rcModelAreaUuid == null ? null : rcModelAreaUuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rc_model_area.rc_model_uuid
     *
     * @return the value of rc_model_area.rc_model_uuid
     *
     * @mbggenerated Mon Oct 30 09:40:36 CST 2017
     */
    public String getRcModelUuid() {
        return rcModelUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rc_model_area.rc_model_uuid
     *
     * @param rcModelUuid the value for rc_model_area.rc_model_uuid
     *
     * @mbggenerated Mon Oct 30 09:40:36 CST 2017
     */
    public void setRcModelUuid(String rcModelUuid) {
        this.rcModelUuid = rcModelUuid == null ? null : rcModelUuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rc_model_area.busi_type
     *
     * @return the value of rc_model_area.busi_type
     *
     * @mbggenerated Mon Oct 30 09:40:36 CST 2017
     */
    public String getBusiType() {
        return busiType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rc_model_area.busi_type
     *
     * @param busiType the value for rc_model_area.busi_type
     *
     * @mbggenerated Mon Oct 30 09:40:36 CST 2017
     */
    public void setBusiType(String busiType) {
        this.busiType = busiType == null ? null : busiType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rc_model_area.area_code
     *
     * @return the value of rc_model_area.area_code
     *
     * @mbggenerated Mon Oct 30 09:40:36 CST 2017
     */
    public String getAreaCode() {
        return areaCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rc_model_area.area_code
     *
     * @param areaCode the value for rc_model_area.area_code
     *
     * @mbggenerated Mon Oct 30 09:40:36 CST 2017
     */
    public void setAreaCode(String areaCode) {
        this.areaCode = areaCode == null ? null : areaCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rc_model_area.area_name
     *
     * @return the value of rc_model_area.area_name
     *
     * @mbggenerated Mon Oct 30 09:40:36 CST 2017
     */
    public String getAreaName() {
        return areaName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rc_model_area.area_name
     *
     * @param areaName the value for rc_model_area.area_name
     *
     * @mbggenerated Mon Oct 30 09:40:36 CST 2017
     */
    public void setAreaName(String areaName) {
        this.areaName = areaName == null ? null : areaName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rc_model_area.remark
     *
     * @return the value of rc_model_area.remark
     *
     * @mbggenerated Mon Oct 30 09:40:36 CST 2017
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rc_model_area.remark
     *
     * @param remark the value for rc_model_area.remark
     *
     * @mbggenerated Mon Oct 30 09:40:36 CST 2017
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rc_model_area.create_time
     *
     * @return the value of rc_model_area.create_time
     *
     * @mbggenerated Mon Oct 30 09:40:36 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rc_model_area.create_time
     *
     * @param createTime the value for rc_model_area.create_time
     *
     * @mbggenerated Mon Oct 30 09:40:36 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rc_model_area.update_time
     *
     * @return the value of rc_model_area.update_time
     *
     * @mbggenerated Mon Oct 30 09:40:36 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rc_model_area.update_time
     *
     * @param updateTime the value for rc_model_area.update_time
     *
     * @mbggenerated Mon Oct 30 09:40:36 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rc_model_area.del_flag
     *
     * @return the value of rc_model_area.del_flag
     *
     * @mbggenerated Mon Oct 30 09:40:36 CST 2017
     */
    public Integer getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rc_model_area.del_flag
     *
     * @param delFlag the value for rc_model_area.del_flag
     *
     * @mbggenerated Mon Oct 30 09:40:36 CST 2017
     */
    public void setDelFlag(Integer delFlag) {
        this.delFlag = delFlag;
    }
}